<?php

declare(strict_types=1);

namespace ModernAuthLab\Security\Totp;

use InvalidArgumentException;

/**
 * Builds the `otpauth://` provisioning URI consumed by authenticator apps.
 *
 * The URI is the text payload that will later be encoded into a QR code. It
 * contains the TOTP secret, so callers must treat the generated URI as
 * security-critical data.
 */
final readonly class TotpProvisioningUri
{
    private const TYPE = 'totp';
    private const SUPPORTED_ALGORITHMS = ['SHA1', 'SHA256', 'SHA512'];
    private const SUPPORTED_DIGITS = [6, 8];

    /**
     * Validate provisioning parameters before building the URI.
     *
     * @param string $issuer Service/provider name shown by authenticator apps.
     * @param string $accountLabel Account label shown by authenticator apps.
     * @param TotpSecret $secret TOTP shared secret.
     * @param string $algorithm HMAC algorithm advertised to the authenticator app.
     * @param int $digits Number of digits generated by the authenticator app.
     * @param int $period Code validity period in seconds.
     *
     * @throws InvalidArgumentException When provisioning parameters are invalid.
     */
    public function __construct(
        private string $issuer,
        private string $accountLabel,
        private TotpSecret $secret,
        private string $algorithm = 'SHA1',
        private int $digits = 6,
        private int $period = 30,
    ) {
        if (trim($this->issuer) === '') {
            throw new InvalidArgumentException('TOTP issuer cannot be empty.');
        }

        if (trim($this->accountLabel) === '') {
            throw new InvalidArgumentException('TOTP account label cannot be empty.');
        }

        if (! in_array($this->algorithm, self::SUPPORTED_ALGORITHMS, true)) {
            throw new InvalidArgumentException('TOTP algorithm must be SHA1, SHA256, or SHA512.');
        }

        if (! in_array($this->digits, self::SUPPORTED_DIGITS, true)) {
            throw new InvalidArgumentException('TOTP digits must be 6 or 8.');
        }

        if ($this->period < 1) {
            throw new InvalidArgumentException('TOTP period must be at least 1 second.');
        }
    }

    /**
     * Build the provisioning URI for QR-code generation or manual setup.
     *
     * @return string `otpauth://` URI containing the TOTP shared secret.
     */
    public function uri(): string
    {
        $label = rawurlencode($this->issuer) . ':' . rawurlencode($this->accountLabel);
        $query = http_build_query([
            'secret' => $this->secret->base32(),
            'issuer' => $this->issuer,
            'algorithm' => $this->algorithm,
            'digits' => $this->digits,
            'period' => $this->period,
        ], '', '&', PHP_QUERY_RFC3986);

        return sprintf('otpauth://%s/%s?%s', self::TYPE, $label, $query);
    }
}
